"""Add recipient_id to Message model

Revision ID: c7a56509e8b2
Revises: 
Create Date: 2024-09-04 01:08:15.532448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7a56509e8b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'sent'::character varying"))
        batch_op.create_foreign_key(None, 'users', ['recipient_id'], ['user_id'])

    with op.batch_alter_table('user_chat', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'participant'::character varying"))

    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.alter_column('last_active',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.alter_column('last_active',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('user_chat', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'participant'::character varying"))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'sent'::character varying"))
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
